... logging to /home/nick/.ros/log/rostest-nick-Precision-T1600-24092.log
[ROSUNIT] Outputting test results to /home/nick/.ros/test_results/test_rosmaster/rostest-test_rosmaster.xml
[Testcase: testtest_rosmaster_registerPublisher_invalid] ... ok
[Testcase: testtest_rosmaster_registerPublisher_success] ... ok
[Testcase: testtest_rosmaster_registerPublisher_types] ... ok
[Testcase: testtest_rosmaster_registerService_invalid] ... ok
[Testcase: testtest_rosmaster_registerService_success] ... ok
[Testcase: testtest_rosmaster_registerSubscriber_invalid] ... ok
[Testcase: testtest_rosmaster_registerSubscriber_simple_success] ... ok
[Testcase: testtest_rosmaster_simple_API] ... ok
[Testcase: testtest_rosmaster_unregisterPublisher_invalid] ... ok
[Testcase: testtest_rosmaster_unregisterPublisher_success] ... ok
[Testcase: testtest_rosmaster_unregisterService_invalid] ... ok
[Testcase: testtest_rosmaster_unregisterService_success] ... ok
[Testcase: testtest_rosmaster_unregisterSubscriber_invalid] ... ok
[Testcase: testtest_rosmaster_unregisterSubscriber_success] ... ok

[ROSTEST]-----------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_registerPublisher_invalid/testRegisterPublisherInvalid][passed]
[test_rosmaster.rosunit-test_rosmaster_registerPublisher_success/testRegisterPublisherSuccess][FAILURE]
master does not know topic type: []
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 62, in testRegisterPublisherSuccess
    self._testRegisterPublisherSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 352, in _testRegisterPublisherSuccess
    self._subTestRegisterPublisherSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 311, in _subTestRegisterPublisherSuccess
    self.assert_([topic_name, topic_type] in val, "master does not know topic type: %s"%val)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_registerPublisher_types/testRegisterPublisherTypes][FAILURE]
status code is not 1: error handling method call 'registerPublisher'
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 66, in testRegisterPublisherTypes
    self._testRegisterPublisherTypes()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 332, in _testRegisterPublisherTypes
    val = self.apiSuccess(master.registerPublisher(caller_id, topic_name, '*', caller_api))
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/rosclient.py", line 61, in apiSuccess
    assert self.last_code == 1, "status code is not 1: %s"%self.last_msg
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_registerService_invalid/testRegisterServiceInvalid][passed]
[test_rosmaster.rosunit-test_rosmaster_registerService_success/testRegisterServiceSuccess][FAILURE]
master service list [['/service-0', ['/service_node', '/service_node', '/service_node', '/service_node', '/service_node']], ['/test_rosmaster_registerService_success/get_loggers', ['/test_rosmaster_registerService_success']], ['/test_rosmaster_registerService_success/set_logger_level', ['/test_rosmaster_registerService_success']]] is missing ['/service-0', ['/service_node']]
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 58, in testRegisterServiceSuccess
    self._testRegisterServiceSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 154, in _testRegisterServiceSuccess
    self._subTestRegisterServiceSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 147, in _subTestRegisterServiceSuccess
    self.assert_(jentry in srvs, "master service list %s is missing %s"%(srvs, jentry))
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_registerSubscriber_invalid/testRegisterSubscriberInvalid][passed]
[test_rosmaster.rosunit-test_rosmaster_registerSubscriber_simple_success/testRegisterSubscriberSimpleSuccess][FAILURE]
status code is not 1: failed to find uri for node at path '/sub_node'
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 70, in testRegisterSubscriberSimpleSuccess
    self._testRegisterSubscriberSimpleSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 434, in _testRegisterSubscriberSimpleSuccess
    self._subTestRegisterSubscriberSimpleSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 419, in _subTestRegisterSubscriberSimpleSuccess
    val = self.apiSuccess(master.lookupNode(self.caller_id, caller_id))
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/rosclient.py", line 61, in apiSuccess
    assert self.last_code == 1, "status code is not 1: %s"%self.last_msg
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_simple_API/testGetPid][passed]
[test_rosmaster.rosunit-test_rosmaster_simple_API/testGetUri][passed]
[test_rosmaster.rosunit-test_rosmaster_unregisterPublisher_invalid/testUnregisterPublisherInvalid][FAILURE]
Call should have returned error -1 code: 'undefined' not registered publisher for topic '/pub_topic'
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 104, in testUnregisterPublisherInvalid
    self._testUnregisterPublisherInvalid()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 254, in _testUnregisterPublisherInvalid
    self.apiError(master.unregisterPublisher(self.caller_id, topic))
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/rosclient.py", line 80, in apiError
    assert self.last_code == -1, "Call should have returned error -1 code: %s"%self.last_msg
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_unregisterPublisher_success/testUnregisterPublisherSuccess][FAILURE]
master does not know topic type: []
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 79, in testUnregisterPublisherSuccess
    self._testUnregisterPublisherSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 369, in _testUnregisterPublisherSuccess
    self._subTestRegisterPublisherSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 311, in _subTestRegisterPublisherSuccess
    self.assert_([topic_name, topic_type] in val, "master does not know topic type: %s"%val)
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_unregisterService_invalid/testUnregisterServiceInvalid][FAILURE]
Call should have returned error -1 code: 'undefined' not registered for service '/service'
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 100, in testUnregisterServiceInvalid
    self._testUnregisterServiceInvalid()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 223, in _testUnregisterServiceInvalid
    self.apiError(master.unregisterService(self.caller_id, service))
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/rosclient.py", line 80, in apiError
    assert self.last_code == -1, "Call should have returned error -1 code: %s"%self.last_msg
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_unregisterService_success/testUnregisterServiceSuccess][FAILURE]
master service list [['/service-0', ['/service_node', '/service_node', '/service_node', '/service_node', '/service_node', '/service_node']], ['/test_rosmaster_unregisterService_success/get_loggers', ['/test_rosmaster_unregisterService_success']], ['/test_rosmaster_unregisterService_success/set_logger_level', ['/test_rosmaster_unregisterService_success']]] is missing ['/service-0', ['/service_node']]
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 75, in testUnregisterServiceSuccess
    self._testUnregisterServiceSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 157, in _testUnregisterServiceSuccess
    self._subTestRegisterServiceSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 147, in _subTestRegisterServiceSuccess
    self.assert_(jentry in srvs, "master service list %s is missing %s"%(srvs, jentry))
  File "/usr/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_unregisterSubscriber_invalid/testUnregisterSubscriberInvalid][FAILURE]
Call should have returned error -1 code: '' not subscribed to topic '/sub_topic'
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 108, in testUnregisterSubscriberInvalid
    self._testUnregisterSubscriberInvalid()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 289, in _testUnregisterSubscriberInvalid
    self.apiError(master.unregisterSubscriber(self.caller_id, topic, ''))
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/rosclient.py", line 80, in apiError
    assert self.last_code == -1, "Call should have returned error -1 code: %s"%self.last_msg
--------------------------------------------------------------------------------

[test_rosmaster.rosunit-test_rosmaster_unregisterSubscriber_success/testUnregisterSubscriberSuccess][FAILURE]
status code is not 1: failed to find uri for node at path '/sub_node'
  File "/usr/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/nick/catkin_new/src/ros_comm/test/test_rosmaster/test/test_master_api.py", line 83, in testUnregisterSubscriberSuccess
    self._testUnregisterSubscriberSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 437, in _testUnregisterSubscriberSuccess
    self._subTestRegisterSubscriberSimpleSuccess()
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/master.py", line 419, in _subTestRegisterSubscriberSimpleSuccess
    val = self.apiSuccess(master.lookupNode(self.caller_id, caller_id))
  File "/home/nick/workspace/ros_comm/test/test_rosmaster/test/rosclient.py", line 61, in apiSuccess
    assert self.last_code == 1, "status code is not 1: %s"%self.last_msg
--------------------------------------------------------------------------------


SUMMARY
 * RESULT: FAIL
 * TESTS: 15
 * ERRORS: 0
 * FAILURES: 10

rostest log file is in /home/nick/.ros/log/rostest-nick-Precision-T1600-24092.log
